#Misc Variables
language: clojure
lein: 2.5.3
sudo: true
branches:
  only:
    - master

#Build
script: "lein cljsbuild once min && lein less once"

#On build success
after_success: 'curl -X GET "https://api.ghostinspector.com/v1/suites/${CFD_GHOST_INSPECTOR_SUITE_ID}/execute/?apiKey=${CFD_GHOST_INSPECTOR_API_KEY}"'

#Deploy
before_deploy: "cd resources/public"
deploy:
  - #Continuous Test
    provider: s3
    access_key_id: ${CFD_OWLET_AWS_ACCESS_KEY_ID}
    secret_access_key: ${CFD_OWLET_AWS_SECRET_ACCESS_KEY}
    bucket: "owlet-dev.codefordenver.org"
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST = false
  - #Production Release
    provider: s3
    access_key_id: ${CFD_OWLET_AWS_ACCESS_KEY_ID}
    secret_access_key: ${CFD_OWLET_AWS_SECRET_ACCESS_KEY}
    bucket: "owlet.codefordenver.org"
    skip_cleanup: true
    on:
      branch: prod
      condition: $TRAVIS_PULL_REQUEST = false

#Test
#after_deploy:
